[package]
name = "tend"
description = "Manager and daemon for long-running CLI commands"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
default-run = "tend"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["derive"] }
windows-service = "0.7.0"
windows-sys = "0.52.0"

[[bin]]
name = "ping_service"
path = "src/ping_service.rs"
