name: install
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  cargo:
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Install
        run: |
          cargo install tend --verbose

      - name: Run
        run: |
          tend --version

  snap:
    runs-on: ubuntu-latest

    steps:
    - name: Update and install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y snapd
        sudo systemctl enable --now snapd.socket
        sudo ln -s /var/lib/snapd/snap /snap

    - name: Ensure snapd is running
      run: |
        sudo systemctl start snapd

    - name: Install
      run: |
        sudo snap install tend

    - name: List installed snaps
      run: |
        snap list

    - name: Run
      run: |
        tend --version

  winget:
    runs-on: windows-latest
    steps:
    - name: Install winget
      uses: Cyberboss/install-winget@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install
      run: |
        winget install lkurcak.tend --disable-interactivity --accept-source-agreements

    - name: List installed packages
      run: |
        winget list

    - name: Add winget links to path
      run: |
        Add-Content $env:GITHUB_PATH "$env:LOCALAPPDATA/Microsoft/WinGet/Links/"

    - name: Run
      run: |
        tend --version
