name: pull request to main

on:
  pull_request:
    branches: 
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build

    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
          - macos-latest
        rust:
          - stable
          - nightly

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Test
        run: cargo test

      - name: Test (Release)
        run: cargo test --release

