name: pull request to main

on:
  pull_request:
    branches: 
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build

    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
          - macos-latest
        toolchain:
          - stable
          - nightly

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose

      - name: Build (Release)
        run: cargo build --release --verbose

      - name: Test (Release)
        run: cargo test --release --verbose

      - name: Check formatting
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy
